font_family JetBrainsMono Nerd Font
font_size 11

disable_ligatures no
enable_audio_bell no

shell_integration disabled

cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0

url_style curly
# window_padding_width 8

background_opacity 0.9

copy_on_select yes
confirm_os_window_close 0

## KDE Specific
# hide_window_decorations yes
# background_blur 24

sync_to_monitor yes

scrollback_lines 10000

repaint_delay 5
input_delay 0

cursor_trail 3
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 0

