### Appearance

# -----------------
# Gaps 
# -----------------
gaps inner 12
gaps outer 6

# -----------------
# Borders
# -----------------
default_border pixel 2
default_floating_border pixel 2
smart_borders on

# -----------------
# Colors (GRUVBOX)
# format: border background text indicator child_border
# -----------------
client.focused          #458588 #458588 #ebdbb2 #458588 #458588
client.unfocused        #282828 #282828 #a89984 #282828 #282828
client.focused_inactive #3c3836 #3c3836 #a89984 #3c3836 #3c3836
client.urgent           #cc241d #cc241d #ebdbb2 #cc241d #cc241d
client.placeholder      #1d2021 #1d2021 #a89984 #1d2021 #1d2021
client.background       #1d2021

# -----------------
# Focus behaviour
# -----------------
focus_follows_mouse yes

