### INPUT

# Keyboard
input type:keyboard {
    xkb_layout "us"
    xkb_numlock enabled
}

# Touchpad
input type:touchpad {
    natural_scroll enabled
    tap enabled
    dwt enabled
}

# Mouse (libinput settings)
input type:pointer {
    accel_profile flat
    pointer_accel 0
}

