### Programs

# Logo key. Use Mod1 for Alt.
set $mod Mod4

# IPC
set $ipc qs -c noctalia-shell ipc call

# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

# Apps
set $term alacritty
set $browser firefox
set $fileManager nautilus
set $music spotify

# Noctalia Actions
set $menu $ipc launcher toggle
set $clipboard $ipc launcher clipboard
set $emoji $ipc launcher emoji
set $lock $ipc lockScreen lock
set $sessionmenu $ipc sessionMenu toggle
set $systemmonitor $ipc systemMonitor toggle
set $settings $ipc settings toggle
set $controlcenter $ipc controlCenter toggle

# Screenshots
set $screenshot_area grim -g "$(slurp)" - | wl-copy
set $screenshot_full grim - | wl-copy

