### Window Rules

## FLOATING RULES

# Dialogs
for_window [window_role="dialog"] floating enable
for_window [window_type="dialog"] floating enable
for_window [app_id="dialog"] floating enable
for_window [app_id="pop-up"] floating enable
for_window [app_id="menu"] floating enable

# Center floating windows
for_window [floating] move position center

