general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    path = /data/Photos and Videos/Wallpapers/gruvbox_forest-4.png
    blur_passes = 0
    blur_size = 0
}

input-field {
    size = 250, 50
    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.2

    outer_color = rgba(d79921ff)   # Gruvbox yellow
    inner_color = rgba(282828cc)   # semi-transparent bg
    font_color = rgba(ebdbb2ff)    # foreground text

    fade_on_empty = false
    placeholder_text = <span foreground="##ebdbb2">Password...</span>

    position = 0, -80
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 64
    color = rgba(ebdbb2ff)

    position = 0, 80
    halign = center
    valign = center
}

label {
    text = cmd[update:60000] echo "$(date +'%A, %d %B')"
    font_size = 18
    color = rgba(a89984ff)

    position = 0, 20
    halign = center
    valign = center
}

