# Sourcing files
source = ~/.config/hypr/conf.d/programs.conf
source = ~/.config/hypr/conf.d/display.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/appearance.conf
source = ~/.config/hypr/conf.d/animations.conf
source = ~/.config/hypr/conf.d/layout.conf
source = ~/.config/hypr/conf.d/autostart.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/misc.conf
source = ~/.config/hypr/conf.d/rules.conf

