general {
    lock_cmd = pidof hyprlock || hyprlock

    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
}

# Dim screen
listener {
    timeout = 570
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Turn monitors off
listener {
    timeout = 600
    on-timeout = niri msg action power-off-monitors
    on-resume = brightnessctl -r && niri msg action power-on-monitors
}

# Lock after
listener {
    timeout = 660
    on-timeout = loginctl lock-session
}
