gpu-api=opengl      # HD 3000 has no Vulkan
hwdec=auto-copy
vo=gpu
profile=fast
 
scale=spline36      # Upscaling (for non-1080p content)
cscale=spline36     # Chroma upscaling
dscale=mitchell     # Downscaling (your main use case — 1080p → 768p)
 
audio-channels=stereo     # Properly downmix 5.1/7.1/Atmos for headphones
save-position-on-quit=yes # Resume where you left off

