vo=gpu
gpu-api=opengl

# Better scaling (visible quality boost, still safe)
scale=lanczos
cscale=lanczos
# dscale=lanczos

# High quality scaling (may lag)
# scale=ewa_lanczossharp
# cscale=ewa_lanczossharp

# video-sync=display-resample
# profile=gpu-hq


