#################
### AUTOSTART ###
#################

# Noctalia Shell
# exec-once = uwsm app -- qs -c noctalia-shell

# Wallpaper
exec-once = uwsm app -- awww-daemon
exec-once = uwsm app -- awww restore 

# Clipboard
exec-once = uwsm app -- wl-paste --type text --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store

