#################
### AUTOSTART ###
#################

# System Services
exec-once = uwsm app -- hyprpolkitagent
exec-once = uwsm app -- hypridle

# UI
exec-once = uwsm app -- waybar
exec-once = uwsm app -- mako

# Wallpaper
exec-once = uwsm app -- awww-daemon
exec-once = uwsm app -- awww restore 

# Night Light
exec-once = uwsm app -- hyprsunset -t 5000 -s 20:30 -e 04:00 -d 30

# Clipboard
exec-once = uwsm app -- wl-paste --type text --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store

