###################
### KEYBINDINGS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, Space, exec, $menu
bind = $mainMod, V, exec, $clipboard
bind = $mainMod, period, exec, $emoji
bind = $mainMod, B, exec, $browser
bind = $mainMod ALT, L, exec, $lock
bind = $mainMod ALT, Q, exec, $sessionmenu
bind = $mainMod, M, exec, $systemmonitor
bind = $mainMod, I, exec, $settings
bind = $mainMod SHIFT, N, exec, $controlcenter
bind = $mainMod, F, fullscreen, 1
bind = $mainMod SHIFT, SPACE, togglefloating,
bind = $mainMod, C, centerwindow,
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod SHIFT, W, layoutmsg, togglesplit # dwindle

# Screenshot
bind = , Print, exec, $screenshot_area
bind = SHIFT, Print, exec, $screenshot_full

# Move focus with mainMod + arrow keys
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Move windows
bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, l, movewindow, r
bind = $mainMod SHIFT, j, movewindow, d
bind = $mainMod SHIFT, k, movewindow, u

# Resize windows
bind = $mainMod, minus, resizeactive, -40 0
bind = $mainMod, equal, resizeactive, 40 0

bind = $mainMod SHIFT, minus, resizeactive, 0 -40
bind = $mainMod SHIFT, equal, resizeactive, 0 40

# Monitor focus
bind = $mainMod ALT, h, focusmonitor, l
bind = $mainMod ALT, l, focusmonitor, r
bind = $mainMod ALT, j, focusmonitor, d
bind = $mainMod ALT, k, focusmonitor, u

# Move window to another monitor
bind = $mainMod ALT SHIFT, h, movewindow, mon:l
bind = $mainMod ALT SHIFT, l, movewindow, mon:r

# Example special workspace (scratchpad)
bind = $mainMod, TAB, workspace, previous
bind = $mainMod SHIFT, TAB, workspace, next
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, $ipc volume increase
bindel = ,XF86AudioLowerVolume, exec, $ipc volume decrease
bindel = ,XF86AudioMute, exec, $ipc volume muteOutput
bindel = ,XF86AudioMicMute, exec, $ipc volume muteInput
bindel = ,XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = ,XF86MonBrightnessDown, exec, $ipc brightness decrease

# Requires playerctl
bindl = , XF86AudioNext, exec, $ipc media next
bindl = , XF86AudioPause, exec, $ipc media playPause
bindl = , XF86AudioPlay, exec, $ipc playPause
bindl = , XF86AudioPrev, exec, $ipc media previous

