###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

#$ipc = qs -c noctalia-shell ipc call
$terminal = kitty
$browser = firefox
$fileManager = nautilus
$music = spotify
# $menu = $ipc launcher toggle
$menu = rofi -show drun
$screenshot_area = grim -g "$(slurp)" - | wl-copy
$screenshot_full = grim - | wl-copy
# $clipboard = $ipc launcher clipboard
$clipboard = cliphist list | rofi -dmenu | cliphist decode | wl-copy
# $emoji = $ipc launcher emoji
$emoji = rofi -show emoji
# $lock = $ipc lockScreen lock
$lock = uwsm app -- hyprlock
# $sessionmenu = $ipc sessionMenu toggle
$sessionmenu = wlogout
# $systemmonitor = $ipc systemMonitor toggle
# $settings = $ipc settings toggle
# $controlcenter = $ipc controlCenter toggle

