general {
    hide_cursor = true
    grace = 2
    disable_loading_bar = true
}

background {
    monitor =
    path = screenshot

    blur_passes = 2
    blur_size = 6

    noise = 0.0117
    contrast = 1.2
    brightness = 0.82
    vibrancy = 0.25
    vibrancy_darkness = 0.15
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"

    color = rgba(cdd6f4ff)

    font_size = 72
    font_family = GeistMono Nerd Font

    position = 0, 140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"

    color = rgba(bac2deff)

    font_size = 18
    font_family = Adwaita Sans

    position = 0, 70
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 260, 52
    outline_thickness = 2

    dots_size = 0.18
    dots_spacing = 0.35
    dots_center = true

    shadow_passes = 2
    shadow_size = 4

    outer_color = rgba(cba6f7ee)
    inner_color = rgba(1e1e2e99)
    font_color = rgba(cdd6f4ff)

    fade_on_empty = false
    placeholder_text = <i>Password...</i>

    hide_input = false

    rounding = 14

    check_color = rgba(a6e3a1ff)
    fail_color = rgba(f38ba8ff)

    capslock_color = rgba(f9e2afff)
    numlock_color = rgba(f9e2afff)

    font_family = Adwaita Sans

    position = 0, -80
    halign = center
    valign = center
}
